
Train Fourcaster
  0%|                                          | 0/92 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/seongbeom/paper/anomaly/main.py", line 182, in <module>
    main()
  File "/home/seongbeom/paper/anomaly/main.py", line 137, in main
    trainer.train(epoch)
  File "/home/seongbeom/paper/anomaly/Trainer.py", line 42, in train
    self.iteration(epoch, self.train_dataloader)
  File "/home/seongbeom/paper/anomaly/Trainer.py", line 102, in iteration
    generated_image, regression_logits = self.model(image_batch[i],self.args)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/seongbeom/paper/anomaly/models.py", line 57, in forward
    x1 = self.inc(x)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/seongbeom/paper/anomaly/layers.py", line 54, in forward
    return self.double_conv(x)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/seongbeom/paper/anomaly/layers.py", line 19, in forward
    x = self.depthwise(x)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/seongbeom/anaconda3/envs/anomaly/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA___conv_depthwise2d)